# Generated by Django 5.1.4 on 2025-01-14 18:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ICD10Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MedicalTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[("MR", "Mr"), ("MS", "Ms"), ("MRS", "Mrs")],
                        max_length=3,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("patient_phone", models.CharField(max_length=20)),
                (
                    "patient_email",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date_of_birth", models.DateField()),
                ("age", models.CharField(blank=True, max_length=4)),
                ("birth_time", models.CharField(max_length=10)),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("patient_id", models.CharField(max_length=20, unique=True)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("street", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "visa_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("visa_type", models.CharField(blank=True, max_length=50, null=True)),
                ("visa_expiry", models.DateField(blank=True, null=True)),
                (
                    "insurance_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "insurance_plan",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("insurance_benefits", models.TextField(blank=True, null=True)),
                (
                    "mrn_number",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "barcode",
                    models.ImageField(blank=True, null=True, upload_to="barcodes/"),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                ("password", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("ad", "Admin"),
                            ("dr", "Doctor"),
                            ("fd", "Frontdesk"),
                            ("nu", "Nurse"),
                            ("ph", "Pharmacist"),
                            ("su", "Superuser"),
                        ],
                        max_length=2,
                    ),
                ),
                ("member_fname", models.CharField(max_length=50)),
                ("member_lname", models.CharField(max_length=50)),
                ("member_phone", models.CharField(max_length=50)),
                ("member_email", models.CharField(max_length=100)),
                ("member_dob", models.DateField()),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("CARDIOVASCULAR", "Cardiovascular"),
                            ("RESPIRATORY", "Respiratory"),
                            ("GASTROINTESTINAL", "Gastrointestinal"),
                            ("NEUROLOGICAL", "Neurological"),
                            ("MUSCULOSKELETAL", "Musculoskeletal"),
                            ("ENDOCRINE", "Endocrine"),
                        ],
                        default="GENERAL",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="CPTCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("description", models.TextField()),
                ("fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "icd10_codes",
                    models.ManyToManyField(
                        related_name="cpt_codes", to="myapp.icd10code"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("generic_name", models.CharField(max_length=200)),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("TABLET", "Tablet"),
                            ("CAPSULE", "Capsule"),
                            ("SYRUP", "Syrup"),
                            ("INJECTION", "Injection"),
                            ("CREAM", "Cream"),
                            ("OINTMENT", "Ointment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("strength", models.CharField(max_length=50)),
                ("contraindications", models.TextField(blank=True)),
                ("side_effects", models.TextField(blank=True)),
                ("recommended_dosage", models.TextField(default=dict)),
                (
                    "icd10_codes",
                    models.ManyToManyField(
                        related_name="medications", to="myapp.icd10code"
                    ),
                ),
                (
                    "interactions",
                    models.ManyToManyField(blank=True, to="myapp.medication"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guarantor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guarantor_name", models.CharField(max_length=100)),
                ("guarantor_relationship", models.CharField(max_length=50)),
                ("guarantor_contact", models.CharField(max_length=20)),
                ("guarantor_address", models.TextField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guarantors",
                        to="myapp.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family_name", models.CharField(max_length=100)),
                ("family_relationship", models.CharField(max_length=50)),
                ("family_contact", models.CharField(max_length=20)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_members",
                        to="myapp.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emergency_name", models.CharField(max_length=100)),
                ("emergency_relationship", models.CharField(max_length=50)),
                ("emergency_phone", models.CharField(max_length=20)),
                (
                    "emergency_email",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="myapp.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diagnosis_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("patient_name", models.CharField(max_length=200)),
                ("diagnosis_date", models.DateTimeField(default=datetime.date.today)),
                ("notes", models.TextField(blank=True, null=True)),
                ("cpt_codes", models.ManyToManyField(to="myapp.cptcode")),
                (
                    "icd10_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.icd10code",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosis",
                        to="myapp.patient",
                    ),
                ),
                ("symptoms", models.ManyToManyField(to="myapp.symptom")),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dosage", models.CharField(default="", max_length=100)),
                ("frequency", models.CharField(default="", max_length=100)),
                ("duration", models.CharField(default="", max_length=100)),
                ("instructions", models.TextField(default="")),
                ("prescribed_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESCRIBED", "Prescribed"),
                            ("DISPENSING", "Dispensing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PRESCRIBED",
                        max_length=20,
                    ),
                ),
                (
                    "medication",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.medication",
                    ),
                ),
                (
                    "patient_diagnosis",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.patientdiagnosis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.doctor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.doctor"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.schedule"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="icd10code",
            name="symptoms",
            field=models.ManyToManyField(to="myapp.symptom"),
        ),
        migrations.CreateModel(
            name="TreatmentProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("procedure_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("preparation_instructions", models.TextField(blank=True)),
                ("scheduled_date", models.DateTimeField()),
                ("department", models.CharField(max_length=100)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("URGENT", "Urgent"),
                            ("HIGH", "High Priority"),
                            ("REGULAR", "Regular"),
                        ],
                        default="REGULAR",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                ("completion_notes", models.TextField(blank=True)),
                ("performed_by", models.CharField(blank=True, max_length=100)),
                ("results_summary", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateTimeField(blank=True, null=True)),
                (
                    "cpt_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.cptcode"
                    ),
                ),
                (
                    "diagnosis_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.patientdiagnosis",
                    ),
                ),
            ],
        ),
    ]
