# Generated by Django 5.1.4 on 2025-01-15 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VitalSigns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("recorded_by", models.CharField(max_length=100)),
                ("temperature", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "temperature_method",
                    models.CharField(
                        choices=[
                            ("ORAL", "Oral"),
                            ("AXILLARY", "Axillary"),
                            ("TYMPANIC", "Tympanic"),
                            ("RECTAL", "Rectal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("systolic_bp", models.IntegerField()),
                ("diastolic_bp", models.IntegerField()),
                ("heart_rate", models.IntegerField()),
                ("respiratory_rate", models.IntegerField()),
                ("oxygen_saturation", models.IntegerField()),
                (
                    "pain_score",
                    models.IntegerField(
                        choices=[
                            (0, "0"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ]
                    ),
                ),
                ("pain_location", models.CharField(blank=True, max_length=100)),
                (
                    "consciousness_level",
                    models.CharField(
                        choices=[
                            ("ALERT", "Alert"),
                            ("VERBAL", "Responds to Verbal"),
                            ("PAIN", "Responds to Pain"),
                            ("UNRESPONSIVE", "Unresponsive"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.patientdiagnosis",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vital Signs",
            },
        ),
    ]
